---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahesh
  labels:
    app: nodejs-springboot
    env: qa
spec:
  selector:
    matchLabels:
      app: nodejs-springboot
  replicas: 1
  template:
    metadata:
      name: mahesh-pod
      labels:
        app: nodejs-springboot
        env: qa
  
    spec:
      containers:
        - name: mahesh-cnt
          image: maheshkumar010/mahesh:latest
          ports:
            - containerPort: 5430
          
          livenessProbe:
            httpGet:
              path: /
              port: 5430
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5430
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
