---
apiVersion: v1
kind: Service
metadata:
  name: mahesh-svc
  labels:
    app: mahesh-app
    env: qa
spec:
  type: LoadBalancer
  ports:
    - port: 5430
      targetPort: 5430
      protocol: TCP
  selector:
    app: mahesh-app
